version: '3'

includes:
  ts:
    taskfile: ./node_modules/@aimarchirico/core-ts/Taskfile.yml
    dir: .

tasks:
  check:
    desc: Run ESLint and TypeScript checks on packages
    cmds:
      - task: ts:check
        vars: {TARGET: '.'}

  fix:
    desc: Auto-fix ESLint issues on packages
    cmds:
      - task: ts:fix
        vars: {TARGET: '.'}
