version: '3'

tasks:
  check:
    desc: Run ESLint and TypeScript checks on packages
    cmds:
      - npx eslint . --no-error-on-unmatched-pattern
      - npx tsc

  fix:
    desc: Auto-fix ESLint issues on packages
    cmds:
      - npx eslint . --fix --no-error-on-unmatched-pattern
