version: '3'

tasks:
  install:
    internal: true
    desc: Install dependencies
    cmds:
      - pnpm install
    if: '[ -n "$CI" ]'

  check:
    desc: Run check script
    cmds:
      - task: install
      - pnpm check

  fix:
    desc: Run fix script
    cmds:
      - task: install
      - pnpm fix