name: Set Up Node
description: Set Up PNPM, Node and Task
inputs:
  cache-dependency-path:
    required: false
    default: npm/pnpm-lock.yaml
  registry-url:
    required: false
    default: ''
  scope:
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Set Up PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 11.9.0

    - name: Set Up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Set Up Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
