version: '3'

dotenv: ['.env']

includes:
  tools:
    taskfile: ./tools/Taskfile.yaml
    dir: ./tools
    flatten: true
  github:
    taskfile: ./.github/Taskfile.yaml
    dir: ./.github
  maven:
    taskfile: ./maven/Taskfile.yaml
    dir: ./maven
  npm:
    taskfile: ./npm/Taskfile.yaml
    dir: ./npm
  python:
    taskfile: ./python/Taskfile.yaml
    dir: ./python
  plugin:
    taskfile: ./plugin/Taskfile.yaml
    dir: ./plugin
  python:
    taskfile: ./python/Taskfile.yaml
    dir: ./python

tasks:
  default:
    cmds:
      - task --list
