version: '3'

dotenv: ['.env']

includes:
  maven:
    taskfile: ./maven/Taskfile.yml
    dir: ./maven
  npm:
    taskfile: ./npm/Taskfile.yml
    dir: ./npm
  tools:
    taskfile: ./tools/Taskfile.yml
    dir: ./tools

tasks:
  default:
    cmds:
      - task --list

  docs:check:
    desc: Lint Markdown files
    cmds:
      - task: tools:docs:check
        vars:
          CLI_ARGS: '{{.CLI_ARGS}}'

  docs:fix:
    desc: Fix Markdown issues
    cmds:
      - task: tools:docs:fix
        vars:
          CLI_ARGS: '{{.CLI_ARGS}}'

  commit:check:
    desc: Lint commit messages
    cmds:
      - task: tools:commit:check
        vars:
          CLI_ARGS: '{{.CLI_ARGS}}'
