name: VPS Deploy
description: Deploy to VPS via SSH
inputs:
  vps_user:
    required: true
  vps_host:
    required: true
  vps_ssh_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Up SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.vps_ssh_key }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        cat >> ~/.ssh/config <<END
        Host vps
          HostName ${{ inputs.vps_host }}
          User ${{ inputs.vps_user }}
          IdentityFile ~/.ssh/deploy_key
          StrictHostKeyChecking no
        END
    - name: Deploy to VPS
      shell: bash
      run: |
        ssh vps "cd ~/docker/${{ github.event.repository.name }} && docker compose pull && docker compose up -d"
