name: Cloudflare Deploy
description: Build and deploy to Cloudflare Pages
inputs:
  build_env:
    required: true
  cloudflare_api_token:
    required: true
  cloudflare_account_id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Web Build
      uses: aimarchirico/commons/.github/actions/node-task@main
      with:
        command: build:web
        working_directory: ./frontend
        task_env: ${{ inputs.build_env }}
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.cloudflare_api_token }}
        accountId: ${{ inputs.cloudflare_account_id }}
        command: pages deploy ./frontend/apps/web/dist --project-name=${{ github.event.repository.name }}-web
