name: Cloudflare Deploy
description: Build and deploy to Cloudflare Pages
inputs:
  command:
    required: true
  node_cache_path:
    required: false
    default: "pnpm-lock.yaml"
  output_directory:
    required: true
  cloudflare_account_id:
    required: true
  cloudflare_api_token:
    required: true
  build_env:
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Web Build
      uses: aimarchirico/commons/.github/actions/node-task@main
      with:
        command: ${{ inputs.command }}
        node_cache_path: ${{ inputs.node_cache_path }}
        task_env: ${{ inputs.build_env }}
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.cloudflare_api_token }}
        accountId: ${{ inputs.cloudflare_account_id }}
        command: pages deploy ${{ inputs.output_directory }} --project-name=${{ github.event.repository.name }}
