name: Set Up Java
description: Set up Java and Task
runs:
  using: composite
  steps:
    - name: Set Up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
        cache: gradle

    - name: Set Up Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
