name: Java Task
description: Run Java CI Task
inputs:
  command:
    required: true
  working_directory:
    required: false
    default: '.'
  task_env:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set Up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
        cache: gradle
    - name: Run Task
      uses: aimarchirico/commons/.github/actions/run-task@main
      with:
        command: ${{ inputs.command }}
        working_directory: ${{ inputs.working_directory }}
        task_env: ${{ inputs.task_env }}
