version: '3'

tasks:
  check:
    desc: Check Python files
    env:
      VIRTUAL_ENV: '{{.TASKFILE_DIR}}/.venv'
    cmds:
      - uv run --package commons-python commons-python ruff check
      - uv run --package commons-python commons-python ty check
      - uv run --package commons-python commons-python commons check
      - uv run --package commons-python commons-python pytest

  fix:
    desc: Fix Python files
    env:
      VIRTUAL_ENV: '{{.TASKFILE_DIR}}/.venv'
    cmds:
      - uv run --package commons-python commons-python ruff check --fix
      - uv run --package commons-python commons-python ruff format
