name: Android Release
description: Build and release Android APK
inputs:
  upload_url:
    required: true
  version:
    required: true
  android_key_alias:
    required: true
  android_key_password:
    required: true
  android_keystore_base64:
    required: true
  android_keystore_password:
    required: true
  build_env:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
        cache: gradle
    - name: JDK 17 for Android Native Build
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'
    - name: Run CI Build for Android
      uses: aimarchirico/commons/.github/actions/node-task@main
      with:
        command: build:android
        working_directory: ./frontend
        task_env: |
          ANDROID_KEY_ALIAS=${{ inputs.android_key_alias }}
          ANDROID_KEY_PASSWORD=${{ inputs.android_key_password }}
          ANDROID_KEYSTORE_BASE64=${{ inputs.android_keystore_base64 }}
          ANDROID_KEYSTORE_PASSWORD=${{ inputs.android_keystore_password }}
          ${{ inputs.build_env }}
    - name: Copy APK
      shell: bash
      run: cp ./frontend/apps/expo/android/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/app-release.apk
    - name: Upload Release Asset to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ inputs.upload_url }}
        asset_path: ${{ github.workspace }}/app-release.apk
        asset_name: ${{ github.event.repository.name }}-${{ inputs.version }}.apk
        asset_content_type: application/vnd.android.package-archive
