name: Android Release
description: Build and release Android APK
inputs:
  version:
    required: true
  upload_url:
    required: true
  android_key_alias:
    required: true
  build_env:
    required: true
  android_keystore_base64:
    required: true
  android_keystore_password:
    required: true
  android_key_password:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Up PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 11.9.0
    - name: Set Up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
        cache-dependency-path: ./frontend/pnpm-lock.yaml
        registry-url: https://npm.pkg.github.com
    - name: Set Up Task
      uses: arduino/setup-task@v2
      with:
        version: 3.51.1
    - name: Set Up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25
        cache: gradle
    - name: Set Up Task (Java)
      uses: arduino/setup-task@v2
      with:
        version: 3.x
    - name: JDK 17 for Android Native Build
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'
    - name: Run CI Build for Android
      working-directory: ./frontend
      shell: bash
      run: |
        echo "${{ inputs.build_env }}" > .env.temp
        source .env.temp
        task build:android
      env:
        ANDROID_KEYSTORE_BASE64: ${{ inputs.android_keystore_base64 }}
        ANDROID_KEYSTORE_PASSWORD: ${{ inputs.android_keystore_password }}
        ANDROID_KEY_ALIAS: ${{ inputs.android_key_alias }}
        ANDROID_KEY_PASSWORD: ${{ inputs.android_key_password }}
    - name: Copy APK
      shell: bash
      run: cp ./frontend/apps/expo/android/app/build/outputs/apk/release/app-release.apk ${{ github.workspace }}/app-release.apk
    - name: Upload Release Asset to GitHub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ inputs.upload_url }}
        asset_path: ${{ github.workspace }}/app-release.apk
        asset_name: ${{ github.event.repository.name }}-${{ inputs.version }}.apk
        asset_content_type: application/vnd.android.package-archive
