name: Close Issues
description: Close issues and PRs related to a branch
inputs:
  branch:
    required: true
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Close Related Issues and PRs
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const branch = '${{ inputs.branch }}';
          
          const issues = await github.rest.search.issuesAndPullRequests({
            q: `repo:${context.repo.owner}/${context.repo.repo} is:open head:${branch}`,
          });

          for (const issue of issues.data.items) {
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed',
            });
            console.log(`Closed issue/PR #${issue.number} related to branch ${branch}`);
          }
