version: '3'

tasks:
  build:
    desc: Run build task
    cmds:
      - bash gradlew build

  check:
    desc: Run check task
    cmds:
      - bash gradlew check

  fix:
    desc: Run ktfmtFormat task
    cmds:
      - bash gradlew ktfmtFormat
