name: Cloudflare Deploy

on:
  workflow_call:
    inputs:
      app_url:
        required: true
        type: string
      cloudflare_account_id:
        required: true
        type: string
    secrets:
      BUILD_ENV:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: web-production
      url: ${{ inputs.app_url }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set Up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 11.9.0

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: ./frontend/pnpm-lock.yaml
          registry-url: https://npm.pkg.github.com

      - name: Set Up Task
        uses: arduino/setup-task@v2
        with:
          version: 3.51.1

      - name: Build for Web
        working-directory: ./frontend
        run: |
          echo "${{ secrets.BUILD_ENV }}" > .env.temp
          source .env.temp
          task build:web

      - name: Publish to Cloudflare Pages
        working-directory: ./frontend
        run: npx wrangler pages deploy ./apps/expo/dist --project-name=${{ github.event.repository.name }} --branch=main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ inputs.cloudflare_account_id }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
