name: VPS Deploy

on:
  workflow_call:
    inputs:
      api_url:
        required: true
        type: string
      vps_host:
        required: true
        type: string
      vps_user:
        required: true
        type: string
    secrets:
      VPS_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: api-production
      url: ${{ inputs.api_url }}
    steps:
      - name: Set Up SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan -H ${{ inputs.vps_host }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/key ${{ inputs.vps_user }}@${{ inputs.vps_host }} 'bash -s' <<'EOF'
          cd ~/docker/${{ github.event.repository.name }}
          docker compose -f compose.yml -f compose.prod.yml up -d --pull always ${{ github.event.repository.name }}-api
          EOF
