packages:
  - 'packages/*'
allowBuilds:
  '@firebase/util': true
  '@openapitools/openapi-generator-cli': true
  'core-js': true
  'protobufjs': true
  'unrs-resolver': true
minimumReleaseAgeExclude:
  - eslint-plugin-jsdoc@63.3.1
